<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_5</name>
   <tag></tag>
   <elementGuidId>5de266e7-aabc-4149-9cee-84f46122c25f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pills-all-course']/div[4]/nav/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.page-item.ga-event-click.active > a.page-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8329b249-c4ac-4bd7-9661-f40cf3077d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>0d6334e7-0d43-4eb6-88ad-f21fd39b1cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/all-courses?page=5</value>
      <webElementGuid>f7e9833d-61ae-430a-b090-77267ae190b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0ec37412-aaa6-4576-8ec4-d92d042d1815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-all-course&quot;)/div[@class=&quot;Pagination&quot;]/nav[1]/ul[@class=&quot;pagination justify-content-center&quot;]/li[@class=&quot;page-item ga-event-click active&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>762209e9-f635-4a9d-b9e5-d7a7b747fb4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-all-course']/div[4]/nav/ul/li[6]/a</value>
      <webElementGuid>5407e5d2-39ab-4fd0-a7a1-ea3fbf323b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'5')])[8]</value>
      <webElementGuid>4b106855-0cd5-4df6-bb39-de45b343c1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::a[5]</value>
      <webElementGuid>2e28cd7b-123d-4603-acc9-c023100a3f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Course Details'])[18]/following::a[6]</value>
      <webElementGuid>cb427c95-5a60-4d00-a23e-f8d03da61833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[6]</value>
      <webElementGuid>50fe24f7-572a-4128-8206-d969c23288ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRENDING CERTIFICATION COURSES'])[1]/preceding::a[7]</value>
      <webElementGuid>4daa9a4b-059a-4bc9-9e0f-146616142eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>4dc741c2-4757-4210-a4f3-8e89802bce5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/all-courses?page=5')]</value>
      <webElementGuid>ef245e03-63ee-4e47-b0ca-0c7709d4c3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[6]/a</value>
      <webElementGuid>c20aec2b-e345-4e12-959c-49d5a0ded049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/all-courses?page=5' and (text() = '5' or . = '5')]</value>
      <webElementGuid>67b51ecc-47fd-4369-805f-9ec8dd096806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
