<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Exploring Courses_open_search_overlay</name>
   <tag></tag>
   <elementGuidId>2b4f818d-225c-4da0-ba9f-a45a988cd790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.open_search_overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>661e3f7b-880f-40be-92d8-558aab9ac94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter Course, Category or keyword</value>
      <webElementGuid>c51d33f2-19c3-460f-bc2d-0620c4c10a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open_search_overlay</value>
      <webElementGuid>dad5050b-bcec-41f7-aab2-bc4c224df265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94356500-04e3-4da6-9fe1-5cc8a60cfc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Course, Category or keyword</value>
      <webElementGuid>9faee70f-4939-410f-a65f-58e38190d060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;header_edureka hdv2_main withoffer mobile_screen&quot;]/nav[@class=&quot;navbar navbar-fixed-top&quot;]/div[@class=&quot;search_header&quot;]/input[@class=&quot;open_search_overlay&quot;]</value>
      <webElementGuid>aaeaee51-3139-47e9-96ac-c1e68d1524ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>019a62b2-50d8-46a0-b81b-e1ff634506b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>67094ff1-ca95-4a73-b47a-bbc9cdb96607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter Course, Category or keyword']</value>
      <webElementGuid>93b2dc16-7b58-45ad-bd46-4e142e5e3e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
